host: "0.0.0.0"
port: 8080
domain: "localhost"
log_file: "application_1.log"
state_file: "state_1.json"

peers:
  - id: "node-2"
    address: "127.0.0.1:8081"
  - id: "node-3"
    address: "127.0.0.1:8082"
