host: "0.0.0.0"
port: 8081
domain: "localhost"
log_file: "application_2.log"
state_file: "state_2.json"
peers:
  - id: "node-1"
    address: "127.0.0.1:8080"
  - id: "node-3"
    address: "127.0.0.1:8082"
