services:
  raft-node-1:
    build: .
    container_name: raft_node_1
    working_dir: /usr/src/app
    environment:
      - RAFT_PORT=8080
      - RAFT_PEERS=raft-node-2:8081,raft-node-3:8082
    expose:
      - "8080"       # visibile agli altri container
    networks:
      - raft_network
    command: ["sh","-c","cargo run --bin server 8080"]

  raft-node-2:
    build: .
    container_name: raft_node_2
    working_dir: /usr/src/app
    environment:
      - RAFT_PORT=8081
      - RAFT_PEERS=raft-node-1:8080,raft-node-3:8082
    expose:
      - "8081"
    networks:
      - raft_network
    depends_on:
      - raft-node-1
    command: ["sh","-c","cargo run --bin server 8081"]

  raft-node-3:
    build: .
    container_name: raft_node_3
    working_dir: /usr/src/app
    environment:
      - RAFT_PORT=8082
      - RAFT_PEERS=raft-node-1:8080,raft-node-2:8081
    expose:
      - "8082"
    networks:
      - raft_network
    depends_on:
      - raft-node-2
    command: ["sh","-c","cargo run --bin server 8082"]

networks:
  raft_network:
    driver: bridge
